import type {
	IDataObject,
	IExecuteFunctions,
	IHttpRequestOptions,
	INodeExecutionData,
	INodeType,
	INodeTypeDescription,
} from 'n8n-workflow';
import { NodeOperationError } from 'n8n-workflow';

/**
 * n8n-Node für die easycompliance-REST-API (Sanktionslisten- & PEP-Prüfung).
 *
 * Die API besteht aus zwei Instanzen (Sanktionslisten / PEP) mit identischem
 * Parametersatz; die URLs sind kundenindividuell und liegen im Credential.
 * Alle Aufrufe sind POST-Requests; der Node sendet den Body als JSON
 * (von der API seit 2026-07 unterstützt), der API-Key wird vom Credential
 * automatisch als Body-Feld "api_key" injiziert.
 *
 * API-Semantik (siehe https://www.easycompliance.de/schnittstellen/api/):
 *  method=1 Einzelprüfung, method=2 Prüfung + Aufnahme ins Monitoring,
 *  method=3 Treffer der letzten 24h, method=4 Datum des letzten Listenupdates,
 *  method=5 Name/Referenz aus dem Monitoring entfernen.
 *  Statuscodes: 200 Treffer/OK, 204 kein Treffer/kein Eintrag,
 *  401 ungültiger Key, 405 kein POST.
 */
export class Easycompliance implements INodeType {
	description: INodeTypeDescription = {
		displayName: 'easycompliance',
		name: 'easycompliance',
		icon: 'file:easycompliance.svg',
		group: ['transform'],
		version: 1,
		subtitle: '={{$parameter["operation"] + ": " + $parameter["list"]}}',
		description: 'Screen business partners against sanctions lists and PEP lists using the easycompliance API',
		defaults: {
			name: 'easycompliance',
		},
		inputs: ['main'],
		outputs: ['main'],
		credentials: [
			{
				name: 'easycomplianceApi',
				required: true,
			},
		],
		properties: [
			{
				displayName: 'List',
				name: 'list',
				type: 'options',
				options: [
					{
						name: 'PEP List',
						value: 'pep',
						description: 'Politically exposed persons (PEP) screening',
					},
					{
						name: 'Sanctions Lists',
						value: 'sanctions',
						description: 'EU/US/HADDEX sanctions list screening',
					},
				],
				default: 'sanctions',
				description: 'Which easycompliance API instance to call',
			},
			{
				displayName: 'Operation',
				name: 'operation',
				type: 'options',
				noDataExpression: true,
				options: [
					{
						name: 'Check Name',
						value: 'check',
						action: 'Check a name',
						description: 'One-time screening of a single name (method=1)',
					},
					{
						name: 'Check Name and Add to Monitoring',
						value: 'checkAndMonitor',
						action: 'Check a name and add it to monitoring',
						description: 'Screen the name and add it to the daily monitoring list (method=2)',
					},
					{
						name: 'Get Last List Update',
						value: 'lastUpdate',
						action: 'Get the date of the last list update',
						description: 'Date of the last sanctions/PEP list update (method=4)',
					},
					{
						name: 'Get Recent Hits',
						value: 'getHits',
						action: 'Get the hits of the last 24 hours',
						description: 'Hits generated by the daily monitoring within the last 24 hours (method=3)',
					},
					{
						name: 'Remove Name From Monitoring',
						value: 'removeName',
						action: 'Remove a name from monitoring',
						description: 'Remove an entry from the daily monitoring list (method=5)',
					},
				],
				default: 'check',
			},
			{
				displayName: 'Name',
				name: 'name',
				type: 'string',
				default: '',
				required: true,
				displayOptions: {
					show: {
						operation: ['check', 'checkAndMonitor'],
					},
				},
				description: 'Name of the organization or person to screen (UTF-8)',
			},
			{
				displayName: 'Reference',
				name: 'ref',
				type: 'string',
				default: '',
				displayOptions: {
					show: {
						operation: ['check', 'checkAndMonitor'],
					},
				},
				description: 'Your own reference, e.g. a customer, supplier or employee number',
			},
			{
				displayName: 'Duplicate Detection',
				name: 'duplicateBy',
				type: 'options',
				options: [
					{
						name: 'By Name',
						value: 'name',
					},
					{
						name: 'By Reference',
						value: 'ref',
					},
				],
				default: 'name',
				displayOptions: {
					show: {
						operation: ['checkAndMonitor'],
					},
				},
				description: 'Whether an entry is considered a duplicate by its name or by its reference when adding it to the monitoring list',
			},
			// Entfernen: beide API-Instanzen löschen wahlweise per Name oder
			// Referenz (Parameter duplicate_by, PEP-Parität seit 2026-07).
			{
				displayName: 'Remove By',
				name: 'removeBy',
				type: 'options',
				options: [
					{
						name: 'By Name',
						value: 'name',
					},
					{
						name: 'By Reference',
						value: 'ref',
					},
				],
				default: 'name',
				displayOptions: {
					show: {
						operation: ['removeName'],
					},
				},
				description: 'Whether to identify the monitoring entry to remove by its name or by its reference',
			},
			{
				displayName: 'Name',
				name: 'nameToRemove',
				type: 'string',
				default: '',
				required: true,
				displayOptions: {
					show: {
						operation: ['removeName'],
					},
					hide: {
						removeBy: ['ref'],
					},
				},
				description: 'Name to remove from the monitoring list',
			},
			{
				displayName: 'Reference',
				name: 'refToRemove',
				type: 'string',
				default: '',
				required: true,
				displayOptions: {
					show: {
						operation: ['removeName'],
						removeBy: ['ref'],
					},
				},
				description: 'Reference of the entry to remove from the monitoring list',
			},
			{
				displayName: 'Additional Options',
				name: 'additionalOptions',
				type: 'collection',
				placeholder: 'Add option',
				default: {},
				displayOptions: {
					show: {
						operation: ['check', 'checkAndMonitor'],
					},
				},
				options: [
					{
						displayName: 'Accuracy',
						name: 'accuracy',
						type: 'number',
						typeOptions: {
							minValue: 50,
							maxValue: 100,
						},
						default: 90,
						description: 'Search accuracy between 50 and 100. If not set, the search pattern configured for your easycompliance account is used.',
					},
					{
						displayName: 'Permutation',
						name: 'permutation',
						type: 'boolean',
						default: false,
						description: 'Whether to also check name variants/permutations (slower response times)',
					},
					{
						displayName: 'Single Word Search',
						name: 'singleWordSearch',
						type: 'options',
						options: [
							{
								name: 'Account Default',
								value: 'default',
							},
							{
								name: 'Disabled',
								value: 'off',
							},
							{
								name: 'Enabled',
								value: 'on',
							},
						],
						default: 'default',
						description: 'Override the single word search option for this request only',
					},
				],
			},
		],
	};

	async execute(this: IExecuteFunctions): Promise<INodeExecutionData[][]> {
		const items = this.getInputData();
		const returnData: INodeExecutionData[] = [];

		const credentials = await this.getCredentials('easycomplianceApi');

		for (let i = 0; i < items.length; i++) {
			try {
				const list = this.getNodeParameter('list', i) as string;
				const operation = this.getNodeParameter('operation', i) as string;

				// API-Instanz je Listentyp aus dem Credential (URLs sind kundenindividuell).
				const url = String(list === 'pep' ? credentials.pepUrl ?? '' : credentials.sanctionsUrl ?? '').trim();
				if (url === '') {
					throw new NodeOperationError(
						this.getNode(),
						list === 'pep'
							? 'No PEP API URL configured in the easycompliance credential'
							: 'No sanctions list API URL configured in the easycompliance credential',
						{ itemIndex: i },
					);
				}

				// Request-Body je Operation aufbauen (method-Codes siehe Klassenkommentar).
				const body: IDataObject = {};
				if (operation === 'check' || operation === 'checkAndMonitor') {
					body.method = operation === 'check' ? 1 : 2;
					body.name = this.getNodeParameter('name', i) as string;
					// Leerer/Whitespace-Name würde serverseitig als leere Suche mit
					// 204 enden und im Workflow als sauberes "kein Treffer" landen,
					// obwohl nichts geprüft wurde (Codex-Review PR #249 Runde 4).
					// Laufzeit-Validierung, damit auch per Expression erzeugte
					// Leerwerte je Item abgefangen werden (UI-required greift dort nicht).
					if (String(body.name).trim() === '') {
						throw new NodeOperationError(this.getNode(), 'Name must not be empty', {
							itemIndex: i,
						});
					}
					const ref = this.getNodeParameter('ref', i, '') as string;
					if (ref !== '') {
						body.ref = ref;
					}
					if (operation === 'checkAndMonitor') {
						body.duplicate_by = this.getNodeParameter('duplicateBy', i, 'name') as string;
						// Leere Referenz bei duplicate_by=ref würde serverseitig still
						// auf Namens-Duplikaterkennung zurückfallen – verschiedene
						// Partner mit gleichem Namen kollabierten dann zu EINEM
						// Monitoring-Eintrag (Codex-Review PR #249 Runde 3). Laufzeit-
						// Validierung statt UI-required, damit auch per Expression
						// erzeugte Leerwerte je Item abgefangen werden.
						if (body.duplicate_by === 'ref' && String(body.ref ?? '').trim() === '') {
							throw new NodeOperationError(
								this.getNode(),
								'Duplicate detection "By Reference" requires a non-empty Reference',
								{ itemIndex: i },
							);
						}
					}
					const extra = this.getNodeParameter('additionalOptions', i, {}) as IDataObject;
					if (extra.accuracy !== undefined) {
						body.accuracy = extra.accuracy;
					}
					if (extra.permutation !== undefined) {
						body.permutation = extra.permutation ? 1 : 0;
					}
					if (extra.singleWordSearch === 'on' || extra.singleWordSearch === 'off') {
						body.single_word_search = extra.singleWordSearch === 'on' ? 1 : 0;
					}
				} else if (operation === 'getHits') {
					body.method = 3;
				} else if (operation === 'lastUpdate') {
					body.method = 4;
				} else if (operation === 'removeName') {
					body.method = 5;
					const removeBy = this.getNodeParameter('removeBy', i, 'name') as string;
					if (removeBy === 'ref') {
						body.duplicate_by = 'ref';
						body.ref = this.getNodeParameter('refToRemove', i) as string;
					} else {
						body.name = this.getNodeParameter('nameToRemove', i) as string;
					}
				}

				// Body als OBJEKT belassen (die Credential-Injection mergt api_key
				// hinein) und den Request explizit als JSON deklarieren. BEWUSST
				// ohne json:true (Codex-Review PR #249 Runde 4): Die API antwortet
				// je nach Operation mit JSON (method 1-3), plain text (method=4,
				// z. B. "31.07.2026") oder leerem Body (204/method=5) - eine
				// erzwungene JSON-Deserialisierung der Antwort dürfte bei den
				// Nicht-JSON-Antworten nicht fehlschlagen. Die Antwort wird unten
				// defensiv normalisiert (geparst ODER Rohstring).
				const requestOptions: IHttpRequestOptions = {
					method: 'POST',
					url,
					headers: { 'content-type': 'application/json' },
					body,
					returnFullResponse: true,
					// Statuscodes selbst auswerten: 204/401 sind fachliche Antworten
					// der API (kein Treffer bzw. Auth-Fehler), keine Transportfehler.
					ignoreHttpStatusErrors: true,
					timeout: 15000,
				};

				const response = (await this.helpers.httpRequestWithAuthentication.call(
					this,
					'easycomplianceApi',
					requestOptions,
				)) as { statusCode: number; body: unknown };

				const statusCode = response.statusCode;
				if (statusCode === 401) {
					throw new NodeOperationError(
						this.getNode(),
						'easycompliance API: invalid API key or account suspended (HTTP 401)',
						{ itemIndex: i },
					);
				}
				if (statusCode === 405) {
					throw new NodeOperationError(
						this.getNode(),
						'easycompliance API: request was rejected as non-POST (HTTP 405) – please report this to easycompliance support',
						{ itemIndex: i },
					);
				}
				if (statusCode !== 200 && statusCode !== 204) {
					throw new NodeOperationError(
						this.getNode(),
						`easycompliance API: unexpected HTTP status ${statusCode}`,
						{ itemIndex: i },
					);
				}

				// Antwort defensiv normalisieren: je nach n8n-Version liefert der
				// HTTP-Helper JSON-Antworten bereits geparst (Array) oder als
				// Rohstring - beide Formen werden akzeptiert.
				let parsedBody: unknown = response.body;
				if (typeof parsedBody === 'string') {
					const trimmedBody = parsedBody.trim();
					if (trimmedBody.startsWith('[') || trimmedBody.startsWith('{')) {
						try {
							parsedBody = JSON.parse(trimmedBody);
						} catch {
							// Rohstring behalten (kein valides JSON)
						}
					}
				}

				// Die API liefert bei Prüf-/Treffer-Operationen 200 AUSSCHLIESSLICH
				// mit einem JSON-Array; "kein Treffer" ist immer 204. Ein 200 ohne
				// Array (abgeschnittene Antwort, Proxy-Fehlerseite, fremder Inhalt)
				// darf deshalb NICHT als hit:false durchgehen, sonst entstünde ein
				// falsch-sauberes Prüfergebnis (Codex-Review PR #249 Runde 5).
				const requireResultArray = (): IDataObject[] => {
					if (statusCode === 200 && !Array.isArray(parsedBody)) {
						throw new NodeOperationError(
							this.getNode(),
							'easycompliance API returned HTTP 200 without a result array – the response may be truncated or malformed',
							{ itemIndex: i },
						);
					}
					return Array.isArray(parsedBody) ? (parsedBody as IDataObject[]) : [];
				};

				// Fachliche Ausgabe je Operation normalisieren (204 = leerer Body).
				let out: IDataObject;
				if (operation === 'check' || operation === 'checkAndMonitor') {
					const hits = requireResultArray();
					out = {
						name: body.name,
						ref: body.ref ?? '',
						hit: hits.length > 0,
						hitCount: hits.length,
						hits,
					};
				} else if (operation === 'getHits') {
					const hits = requireResultArray();
					out = {
						hitCount: hits.length,
						hits,
					};
				} else if (operation === 'lastUpdate') {
					out = {
						lastUpdate: String(response.body ?? '').trim(),
					};
				} else {
					// removeName: 200 = Eintrag war vorhanden und wurde entfernt, 204 = nicht gefunden.
					out = {
						removed: statusCode === 200,
					};
				}

				returnData.push({ json: out, pairedItem: { item: i } });
			} catch (error) {
				if (this.continueOnFail()) {
					returnData.push({
						json: { error: (error as Error).message },
						pairedItem: { item: i },
					});
					continue;
				}
				throw error;
			}
		}

		return [returnData];
	}
}
